# Generated by Django 6.0.3 on 2026-03-15 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatkaNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('M_time_1', models.CharField(max_length=100)),
                ('M_time_2', models.CharField(max_length=100)),
                ('M_Name', models.CharField(max_length=100)),
                ('M_Number_1', models.CharField(max_length=100)),
                ('M_Number_2', models.CharField(max_length=100)),
                ('M_Number_3', models.CharField(max_length=100)),
            ],
        ),
    ]
