# Generated by Django 6.0.3 on 2026-03-21 22:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('open_start_time', models.TimeField(help_text='Time when Open betting starts')),
                ('open_end_time', models.TimeField(help_text='Official Open end time')),
                ('close_start_time', models.TimeField(help_text='Time when Close betting starts')),
                ('close_end_time', models.TimeField(help_text='Official Close end time')),
                ('open_patti', models.CharField(blank=True, help_text='e.g. 123', max_length=3, null=True)),
                ('open_single', models.CharField(blank=True, help_text='e.g. 6', max_length=1, null=True)),
                ('close_single', models.CharField(blank=True, help_text='e.g. 7', max_length=1, null=True)),
                ('close_patti', models.CharField(blank=True, help_text='e.g. 601', max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[('SINGLE', 'Single'), ('JODI', 'Jodi'), ('SINGLE_PATTI', 'Single Patti'), ('DOUBLE_PATTI', 'Double Patti'), ('TRIPLE_PATTI', 'Triple Patti')], max_length=20)),
                ('session', models.CharField(choices=[('OPEN', 'Open'), ('CLOSE', 'Close')], max_length=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_id_str', models.CharField(help_text='Unique User ID string for filtering', max_length=50)),
                ('number', models.CharField(max_length=10)),
                ('amount', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('WIN', 'Win'), ('LOSS', 'Loss')], default='PENDING', max_length=10)),
                ('win_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='MATKAAPP.market')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('profile_pic', models.ImageField(blank=True, default='profile_pics/default.png', upload_to='profile_pics/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('txn_type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('BET', 'Bet Placed'), ('WIN', 'Winning Credit')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='MATKAAPP.wallet')),
            ],
        ),
    ]
