# Generated by Django 6.0.3 on 2026-03-21 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MATKAAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationCounter',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Registration counter',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='user_code',
            field=models.CharField(blank=True, help_text='Public ID e.g. KMWU0001', max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile',
            field=models.CharField(blank=True, help_text='Normalized 10-digit Indian mobile; unique per account.', max_length=15, null=True, unique=True),
        ),
    ]
