# Generated by Django 6.0.3 on 2026-03-15 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MATKAAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matkanumber',
            name='M_time_1',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='matkanumber',
            name='M_time_2',
            field=models.TimeField(),
        ),
    ]
