# Generated by Django 6.0.3 on 2026-03-15 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MATKAAPP', '0002_alter_matkanumber_m_time_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matkanumber',
            name='M_Name',
        ),
        migrations.RemoveField(
            model_name='matkanumber',
            name='M_Number_1',
        ),
        migrations.RemoveField(
            model_name='matkanumber',
            name='M_Number_2',
        ),
        migrations.RemoveField(
            model_name='matkanumber',
            name='M_Number_3',
        ),
        migrations.RemoveField(
            model_name='matkanumber',
            name='M_time_1',
        ),
        migrations.RemoveField(
            model_name='matkanumber',
            name='M_time_2',
        ),
        migrations.AddField(
            model_name='matkanumber',
            name='m_name',
            field=models.CharField(blank=True, default='Lucky Drop', max_length=100, verbose_name='Market Name'),
        ),
        migrations.AddField(
            model_name='matkanumber',
            name='m_number_1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Number 1'),
        ),
        migrations.AddField(
            model_name='matkanumber',
            name='m_number_2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Number 2'),
        ),
        migrations.AddField(
            model_name='matkanumber',
            name='m_number_3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Number 3'),
        ),
        migrations.AddField(
            model_name='matkanumber',
            name='m_time_1',
            field=models.TimeField(blank=True, null=True, verbose_name='Opening Time'),
        ),
        migrations.AddField(
            model_name='matkanumber',
            name='m_time_2',
            field=models.TimeField(blank=True, null=True, verbose_name='Closing Time'),
        ),
    ]
