# Generated by Django 6.0.3 on 2026-03-15 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MATKAAPP', '0003_remove_matkanumber_m_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matkanumber',
            name='m_name',
            field=models.CharField(blank=True, default='Lucky Drop', max_length=100),
        ),
        migrations.AlterField(
            model_name='matkanumber',
            name='m_number_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='matkanumber',
            name='m_number_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='matkanumber',
            name='m_number_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
