# Generated by Django 6.0.3 on 2026-03-15 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MATKAAPP', '0004_alter_matkanumber_m_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matkanumber',
            name='m_number_4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
