# Generated by Django 5.2.12 on 2026-03-17 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MATKAAPP", "0005_matkanumber_m_number_4"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matkanumber",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
