# Generated by Django 6.0.3 on 2026-03-22 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MATKAAPP', '0005_profile_is_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='close_patti',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='market',
            name='close_single',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='market',
            name='open_patti',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='market',
            name='open_single',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
