# Generated by Django 6.0.3 on 2026-03-22 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MATKAAPP', '0006_alter_market_close_patti_alter_market_close_single_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTPVerification',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_mobile_verified',
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
