# Generated by Django 6.0.3 on 2026-03-22 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MATKAAPP', '0008_alter_profile_user_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentOrder',
        ),
    ]
