# Generated by Django 6.0.3 on 2026-03-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MATKAAPP', '0009_delete_paymentorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
