# Generated by Django 6.0.3 on 2026-03-24 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MATKAAPP', '0011_withdrawalrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='collection_date',
            field=models.DateTimeField(blank=True, help_text='Market specific collection date and time', null=True),
        ),
    ]
