# Generated by Django 6.0.3 on 2026-03-25 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MATKAAPP', '0012_market_collection_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='close_end_time',
            field=models.DateTimeField(help_text='Official Close end time'),
        ),
        migrations.AlterField(
            model_name='market',
            name='close_start_time',
            field=models.DateTimeField(help_text='Time when Close betting starts'),
        ),
        migrations.AlterField(
            model_name='market',
            name='open_end_time',
            field=models.DateTimeField(help_text='Official Open end time'),
        ),
        migrations.AlterField(
            model_name='market',
            name='open_start_time',
            field=models.DateTimeField(help_text='Time when Open betting starts'),
        ),
    ]
