# Generated by Django 6.0.3 on 2026-03-25 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MATKAAPP', '0013_alter_market_close_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='credited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bet',
            name='is_credited',
            field=models.BooleanField(default=False, help_text='True if winning amount is added to wallet'),
        ),
        migrations.AddField(
            model_name='market',
            name='close_declared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='market',
            name='open_declared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
