# Generated by Django 6.0.3 on 2026-03-28 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MATKAAPP', '0015_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_date', models.DateTimeField(blank=True, null=True)),
                ('open_patti', models.CharField(blank=True, max_length=3, null=True)),
                ('open_single', models.CharField(blank=True, max_length=1, null=True)),
                ('close_patti', models.CharField(blank=True, max_length=3, null=True)),
                ('close_single', models.CharField(blank=True, max_length=1, null=True)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='MATKAAPP.market')),
            ],
            options={
                'ordering': ['-archived_at'],
            },
        ),
    ]
