# Generated by Django 6.0.3 on 2026-03-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MATKAAPP', '0016_markethistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='close_end_time',
            field=models.DateTimeField(blank=True, help_text='Official Close end time', null=True),
        ),
        migrations.AlterField(
            model_name='market',
            name='close_start_time',
            field=models.DateTimeField(blank=True, help_text='Time when Close betting starts', null=True),
        ),
        migrations.AlterField(
            model_name='market',
            name='open_end_time',
            field=models.DateTimeField(blank=True, help_text='Official Open end time', null=True),
        ),
        migrations.AlterField(
            model_name='market',
            name='open_start_time',
            field=models.DateTimeField(blank=True, help_text='Time when Open betting starts', null=True),
        ),
    ]
