# Generated by Django 6.0.3 on 2026-03-31 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MATKAAPP', '0018_paymentsettings_sitesettings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='is_captcha_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
