# Generated by Django 6.0.3 on 2026-03-31 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MATKAAPP', '0021_bet_deleted_at_bet_is_deleted_useractivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='auto_delete',
            field=models.BooleanField(default=False, help_text='If True, delete 30 mins after being read'),
        ),
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_images/'),
        ),
        migrations.AddField(
            model_name='message',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
