# Generated by Django 6.0.3 on 2026-04-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MATKAAPP', '0022_message_auto_delete_message_image_message_read_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsettings',
            name='payee_name',
            field=models.CharField(default='Payee Name', help_text='Should match the name registered with the bank/UPI ID', max_length=255),
        ),
    ]
