# Generated by Django 6.0.3 on 2026-04-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MATKAAPP', '0023_paymentsettings_payee_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depositrequest',
            name='txn_ref',
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='upi_id',
            field=models.CharField(default='8217228766', max_length=255),
        ),
    ]
