# Generated by Django 6.0.3 on 2026-04-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MATKAAPP', '0025_sitesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='is_captcha_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
