# Generated by Django 6.0.3 on 2026-04-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MATKAAPP', '0026_alter_sitesettings_is_captcha_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='bank_holder_name',
            field=models.CharField(blank=True, help_text='Name as per Bank', max_length=100, null=True),
        ),
    ]
