# Generated by Django 6.0.3 on 2026-04-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MATKAAPP', '0027_withdrawalrequest_bank_holder_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='admin_pin',
            field=models.CharField(blank=True, default='123456', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='admin_security_answer',
            field=models.CharField(blank=True, default='Gandu', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='admin_security_question',
            field=models.CharField(blank=True, default='My favourite name', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='is_captcha_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
