# Generated by Django 6.0.3 on 2026-04-19 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MATKAAPP', '0028_profile_admin_pin_profile_admin_security_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='webauthn_credential',
            field=models.JSONField(blank=True, help_text='Stored WebAuthn credential for biometric auth', null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='is_captcha_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
