# Generated by Django 6.0.3 on 2026-04-25 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MATKAAPP', '0029_profile_webauthn_credential_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='webauthn_credential',
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, help_text='User email (Yahoo/Gmail/etc) used for OTP verification.', max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_hash', models.CharField(max_length=128)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_sent_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_otp', to='MATKAAPP.profile')),
            ],
            options={
                'indexes': [models.Index(fields=['expires_at'], name='MATKAAPP_em_expires_54881b_idx'), models.Index(fields=['last_sent_at'], name='MATKAAPP_em_last_se_dde65a_idx')],
            },
        ),
    ]
