# Generated by Django 6.0.3 on 2026-04-26 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MATKAAPP', '0030_remove_profile_webauthn_credential_profile_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteSettings',
        ),
    ]
