# Generated by Django 6.0.3 on 2026-04-27 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MATKAAPP', '0031_delete_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='email',
            field=models.EmailField(blank=True, help_text='Used for OTP before user creation', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_otp', to='MATKAAPP.profile'),
        ),
        migrations.AddIndex(
            model_name='emailotp',
            index=models.Index(fields=['email'], name='MATKAAPP_em_email_fbfabe_idx'),
        ),
    ]
