# Generated by Django 6.0.3 on 2026-04-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MATKAAPP', '0032_emailotp_email_alter_emailotp_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='support_whatsapp_number',
            field=models.CharField(blank=True, default='', help_text='Support WhatsApp number in international format, e.g. 918217228765', max_length=20),
        ),
    ]
