# Generated by Django 6.0.3 on 2026-04-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MATKAAPP', '0033_profile_support_whatsapp_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='close_duration_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Persisted countdown duration for the close session in minutes.', null=True),
        ),
        migrations.AddField(
            model_name='market',
            name='open_duration_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Persisted countdown duration for the open session in minutes.', null=True),
        ),
    ]
