"""
Django settings for MATKA project.

Generated by 'django-admin startproject' using Django 6.0.3.
"""

from pathlib import Path
import os
import logging.handlers
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env file from absolute path
load_dotenv(os.path.join(BASE_DIR, ".env"))

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")
if not SECRET_KEY or SECRET_KEY.startswith("django-insecure") or len(SECRET_KEY) < 50:
    if os.getenv("DEBUG", "False") == "True":
        # Development only — never reaches production
        SECRET_KEY = "django-insecure-dev-only-not-for-production-use-at-all"
    else:
        raise RuntimeError(
            "SECRET_KEY is missing or insecure. "
            "Set a strong SECRET_KEY in your .env file before running in production."
        )

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False") == "True"

ALLOWED_HOSTS_ENV = os.getenv("ALLOWED_HOSTS", "*")
ALLOWED_HOSTS = [host.strip().strip('"').strip("'") for host in ALLOWED_HOSTS_ENV.split(",") if host.strip()]

# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "axes",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "allauth.socialaccount.providers.facebook",
    "allauth.socialaccount.providers.telegram",
    "MATKAAPP",
]

SITE_ID = 1

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "MATKAAPP.middleware.GatekeeperMiddleware",
    "MATKAAPP.middleware.SecurityHeadersMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "axes.middleware.AxesMiddleware",
    "MATKAAPP.middleware.ContentSecurityPolicyMiddleware",
    "MATKAAPP.middleware.OneSessionPerUserMiddleware",
    "MATKAAPP.middleware.Admin2FAMiddleware",
    "MATKAAPP.middleware.SessionTimeoutMiddleware",
    "MATKAAPP.middleware.DelayedWinningCreditMiddleware",
]

# Security Settings
if not DEBUG:
    # Cookies
    CSRF_COOKIE_HTTPONLY = True
    SESSION_COOKIE_HTTPONLY = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SAMESITE = "Lax"
    SESSION_COOKIE_SAMESITE = "Lax"

    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_SSL_REDIRECT = True
    # Extra protection for production
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_REFERRER_POLICY = "same-origin"
    SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin"
    X_FRAME_OPTIONS = "DENY"
else:
    CSRF_COOKIE_HTTPONLY = True
    SESSION_COOKIE_HTTPONLY = True
    CSRF_COOKIE_SECURE = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SAMESITE = "Lax"
    SESSION_COOKIE_SAMESITE = "Lax"
    SECURE_BROWSER_XSS_FILTER = False
    SECURE_CONTENT_TYPE_NOSNIFF = False
    SECURE_SSL_REDIRECT = False
    SECURE_REFERRER_POLICY = "same-origin"
    SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin"
    X_FRAME_OPTIONS = "DENY"

# Axes Settings
AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = 1  # 1 hour cooloff
AXES_LOCKOUT_TEMPLATE = 'auth/lockout.html'
AXES_RESET_ON_SUCCESS = True
AXES_LOCK_OUT_AT_FAILURE = True
AXES_WHITELIST_CALLABLE = "MATKAAPP.axes_utils.axes_whitelist"

AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Django Allauth Settings
ACCOUNT_AUTHENTICATION_METHOD = 'username_email'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = 'optional'
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_USERNAME_REQUIRED = True
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True
ACCOUNT_LOGOUT_ON_GET = True
ACCOUNT_SESSION_REMEMBER = True

# Social Auth Providers
SOCIALACCOUNT_AUTO_SIGNUP = False
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True
SOCIALACCOUNT_QUERY_EMAIL = True
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': os.getenv('GOOGLE_CLIENT_ID', ''),
            'secret': os.getenv('GOOGLE_CLIENT_SECRET', ''),
            'key': ''
        },
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
    },
    'facebook': {
        'APP': {
            'client_id': os.getenv('FACEBOOK_APP_ID', ''),
            'secret': os.getenv('FACEBOOK_APP_SECRET', ''),
            'key': ''
        },
        'SCOPE': ['email', 'public_profile'],
        'METHOD': 'oauth2',
    },
    'telegram': {
        'APP': {
            'client_id': os.getenv('TELEGRAM_BOT_TOKEN', ''),
            'secret': os.getenv('TELEGRAM_BOT_USERNAME', ''),
            'key': ''
        },
    },
}

# reCAPTCHA Keys — must be set in .env; no hardcoded fallback
RECAPTCHA_SITE_KEY = os.getenv("RECAPTCHA_SITE_KEY", "")
RECAPTCHA_SECRET_KEY = os.getenv("RECAPTCHA_SECRET_KEY", "")

# File Upload Restrictions
ALLOWED_EXTENSIONS = ['jpg', 'png', 'pdf']
PROFILE_PIC_MAX_BYTES = int(os.getenv("PROFILE_PIC_MAX_BYTES", str(2 * 1024 * 1024)))

# Session Security
SESSION_COOKIE_AGE = 1800  # 30 minutes in seconds
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_TIMEOUT_SECONDS = 1800  # 30 minutes

# django-csp baseline policy
CSP_DEFAULT_SRC = ("'self'",)
CSP_STYLE_SRC = ("'self'", "'unsafe-inline'", "https://fonts.googleapis.com", "https://cdnjs.cloudflare.com")
CSP_FONT_SRC = ("'self'", "https://fonts.gstatic.com", "https://cdnjs.cloudflare.com", "data:")
CSP_SCRIPT_SRC = ("'self'", "'unsafe-inline'", "https://cdnjs.cloudflare.com")
CSP_IMG_SRC = ("'self'", "data:", "https:")
CSP_CONNECT_SRC = ("'self'", "https:")
CSP_FRAME_SRC = ("'self'",)
CSP_OBJECT_SRC = ("'none'",)
CSP_BASE_URI = ("'self'",)
CSP_FORM_ACTION = ("'self'",)

# django-ratelimit defaults
RATELIMIT_USE_CACHE = "default"
RATELIMIT_VIEW = "MATKAAPP.views.ratelimit_exceeded"


ROOT_URLCONF = "MATKA.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.media",  # Add this for media files in templates
                "MATKAAPP.context_processors.admin_ui_context",
            ],
        },
    },
]

WSGI_APPLICATION = "MATKA.wsgi.application"

# Database
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {"min_length": 6},
    },
    {
        "NAME": "MATKAAPP.validators.MaximumLengthValidator",
        "OPTIONS": {"max_length": 15},
    },
]

# Internationalization
LANGUAGE_CODE = "en-us"
TIME_ZONE = "Asia/Kolkata"
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Media files (User uploaded content)
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Storage backends
USE_MANIFEST_STATIC_FILES = os.getenv("USE_MANIFEST_STATIC_FILES", "False") == "True"
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": (
            "whitenoise.storage.CompressedManifestStaticFilesStorage"
            if USE_MANIFEST_STATIC_FILES
            else "whitenoise.storage.CompressedStaticFilesStorage"
        ),
    },
}

# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Authentication URLs
LOGIN_URL = "login"  # URL name for login page
LOGIN_REDIRECT_URL = "user_home"  # Where to redirect after login
LOGOUT_REDIRECT_URL = "user_home"  # Where to redirect after logout


# Trust origins when behind a proxy/domain (needed to avoid CSRF false 403s on production).
# Example: CSRF_TRUSTED_ORIGINS="https://changelifewithnumbers.pythonanywhere.com"
CSRF_TRUSTED_ORIGINS_ENV = os.getenv("CSRF_TRUSTED_ORIGINS", "")
CSRF_TRUSTED_ORIGINS = [o.strip() for o in CSRF_TRUSTED_ORIGINS_ENV.split(",") if o.strip()]

# Custom CSRF failure handler (shows friendly page; still 403).
CSRF_FAILURE_VIEW = "MATKAAPP.views.csrf_failure"

# --- Email (provider-agnostic; free-tier hosting friendly) ---
# Supports:
# - EMAIL_PROVIDER=gmail    -> smtp.gmail.com + Gmail App Password
# - EMAIL_PROVIDER=smtp     -> fully custom SMTP via EMAIL_HOST/EMAIL_PORT/etc
EMAIL_PROVIDER = (os.getenv("EMAIL_PROVIDER", "gmail") or "gmail").strip().lower()
EMAIL_BACKEND = os.getenv("EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend")

if EMAIL_PROVIDER == "gmail":
    EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.gmail.com")
    EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
    EMAIL_USE_TLS = True
    EMAIL_USE_SSL = False
    EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "").strip()
    # IMPORTANT: Use a 16-character Gmail App Password (Google Account → Security → App Passwords).
    # Do NOT use your normal Gmail password.
    EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "").strip()
else:
    EMAIL_HOST = os.getenv("EMAIL_HOST", "localhost")
    EMAIL_PORT = int(os.getenv("EMAIL_PORT", "25"))
    EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "False") == "True"
    EMAIL_USE_SSL = os.getenv("EMAIL_USE_SSL", "False") == "True"
    EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
    EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")

# Sender name shown in the recipient's inbox.
# Format: "Display Name <address@domain.com>"
# Override via DEFAULT_FROM_EMAIL in .env for production.
DEFAULT_FROM_EMAIL = os.getenv(
    "DEFAULT_FROM_EMAIL",
    "ChangeLifeWithNumbers <changelifewithnumbers@gmail.com>",
)
SERVER_EMAIL = os.getenv("SERVER_EMAIL", DEFAULT_FROM_EMAIL)

# In local development, default to console backend if SMTP isn't configured.
# This prevents signup/OTP from crashing when no mail server is reachable.
if DEBUG and not EMAIL_HOST_USER and not EMAIL_HOST_PASSWORD:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

# --- Email OTP settings ---
EMAIL_OTP_TTL_SECONDS = int(os.getenv("EMAIL_OTP_TTL_SECONDS", os.getenv("OTP_TTL_SECONDS", "300")))
EMAIL_OTP_MAX_ATTEMPTS = int(os.getenv("EMAIL_OTP_MAX_ATTEMPTS", os.getenv("OTP_MAX_ATTEMPTS", "5")))
EMAIL_OTP_RESEND_COOLDOWN_SECONDS = int(
    os.getenv("EMAIL_OTP_RESEND_COOLDOWN_SECONDS", os.getenv("OTP_RESEND_COOLDOWN_SECONDS", "60"))
)

# Logging configuration
ENABLE_FILE_LOGGING = os.getenv("ENABLE_FILE_LOGGING", "False") == "True"

log_handlers = {
    "console": {
        "level": "WARNING",
        "class": "logging.StreamHandler",
        "formatter": "verbose",
    },
}

if ENABLE_FILE_LOGGING:
    log_handlers["file"] = {
        "level": "INFO",
        "class": "logging.handlers.RotatingFileHandler",
        "filename": os.path.join(BASE_DIR, "debug.log"),
        "maxBytes": 5 * 1024 * 1024,   # 5 MB
        "backupCount": 3,
        "formatter": "verbose",
    }

active_handlers = list(log_handlers.keys())

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "handlers": log_handlers,
    "root": {
        # Catch-all: any logger that doesn't match below bubbles up here
        "handlers": active_handlers,
        "level": "WARNING",
    },
    "loggers": {
        "django": {
            "handlers": active_handlers,
            "level": "WARNING",
            "propagate": False,
        },
        "django.request": {
            # Logs 4xx/5xx with full tracebacks
            "handlers": active_handlers,
            "level": "ERROR",
            "propagate": False,
        },
        "django.security": {
            "handlers": active_handlers,
            "level": "WARNING",
            "propagate": False,
        },
        "MATKAAPP": {
            "handlers": active_handlers,
            "level": "INFO",
            "propagate": False,
        },
        "MATKAAPP.middleware": {
            "handlers": active_handlers,
            "level": "INFO",
            "propagate": False,
        },
    },
}
