"""
Django settings for MATKA project.

Generated by 'django-admin startproject' using Django 6.0.3.
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-s$-ze+8omuezrz=(2!wnnwn+)d5h0nbaeep$@4zc)x%eomv2za"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "MATKAAPP",
    "django_recaptcha",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "MATKAAPP.middleware.OneSessionPerUserMiddleware",
    "MATKAAPP.middleware.SessionTimeoutMiddleware",
    "MATKAAPP.middleware.DelayedWinningCreditMiddleware",
]

# Session Security
SESSION_COOKIE_AGE = 600  # 10 minutes in seconds
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_TIMEOUT_SECONDS = 600  # 10 minutes


ROOT_URLCONF = "MATKA.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.media",  # Add this for media files in templates
                "MATKAAPP.views._get_admin_notifications",  # Added for admin dots
            ],
        },
    },
]

WSGI_APPLICATION = "MATKA.wsgi.application"

# Database
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {"min_length": 6},
    },
    {
        "NAME": "MATKAAPP.validators.MaximumLengthValidator",
        "OPTIONS": {"max_length": 15},
    },
]

# Internationalization
LANGUAGE_CODE = "en-us"
TIME_ZONE = "Asia/Kolkata"
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Media files (User uploaded content)
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Storage backends
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Authentication URLs
LOGIN_URL = "login"  # URL name for login page
LOGIN_REDIRECT_URL = "index"  # Where to redirect after login
LOGOUT_REDIRECT_URL = "index"  # Where to redirect after logout


# Google reCAPTCHA Keys
RECAPTCHA_PUBLIC_KEY = "6Lc17JcsAAAAAK9AT9bYN8BaWSJnoozc4p8nS_5b"
RECAPTCHA_PRIVATE_KEY = "6Lc17JcsAAAAAGKkC12Ig19GjFmSQtlVW8HHnsX9"

# Optional: PythonAnywhere usually works fine, but you can force
# the use of HTTPS for the verification request:
RECAPTCHA_USE_SSL = True
RECAPTCHA_VERIFY_TIMEOUT = 10
RECAPTCHA_OPTIONS = {"theme": "light"}  # for django-recaptcha
