# Generated by Django 6.0.3 on 2026-03-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MATKAAPP', '0007_delete_otpverification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_code',
            field=models.CharField(blank=True, editable=False, help_text='Public ID e.g. KMWU0001', max_length=12, null=True, unique=True),
        ),
    ]
